# server version
version: v1.5.3

server:
  # 本工程服务端口，端口被占用则修改
  port: 5004
  servlet:
    context-path: /WeBASE-Sign
  tomcat:
    max-threads: 200       #default 200
    max-connections: 10000  #default 10000

spring:
  cache:
    type: simple
  datasource:
    driver-class-name: com.highgo.jdbc.Driver
    url: jdbc:highgo://119.45.242.41:5866/webasesign #替换对应IP和地址
    username: "sysdba"
    password: "1qaz2wsx!@#$RFV"
  # fix swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

constant: 
  # aes加密key（16位）
  aesKey: EfdsW23D23d3df43
  # aes加密模式 v1.4.0+ 默认CBC（v1.4.0前默认为ECB）
  aesPattern: CBC
  keepAliveRequests: 100
  syncUsrCacheTaskFixedDelay: 10000
  # 返回值是否支持私钥传输
  supportPrivateKeyTransfer: true

mybatis: 
  mapper-locations: classpath:mapper/*.xml

logging: 
  config: classpath:log4j2.xml
